# -*- coding: utf-8 -*-
"""streamlit_app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M3df1Qi7u4DCd8V_X5aVQ9sHcUCfu_bS
"""

import streamlit as st
import pickle

# Load trained model and vectorizer
with open("phishing_model.pkl", "rb") as f:
    model = pickle.load(f)

with open("vectorizer.pkl", "rb") as f:
    vectorizer = pickle.load(f)

# Streamlit UI
st.set_page_config(page_title="PhishGuard 🛡️", layout="centered")
st.title("🛡️ PhishGuard – Phishing Email Detector")
st.write("Paste an email message below to check if it is **phishing** or **legitimate**.")

# Text input
email_input = st.text_area("📧 Email Text", height=250)

# Predict
if st.button("🔍 Detect"):
    if not email_input.strip():
        st.warning("Please enter some email content.")
    else:
        input_vector = vectorizer.transform([email_input])
        prediction = model.predict(input_vector)[0]
        result = "⚠️ Phishing Email" if prediction == 1 else "✅ Legitimate Email"
        st.subheader(f"Result: {result}")